<?
if ($this->updateright) {
?>
<script type="text/javascript">
    top.frames['right'].location.href='about:blank';
</script>
<?
};
//0var_dump($_SESSION);
?>
<nobr>
    <a href="<?=my7::baseurl()?>a7-left/mainmenu">Главное меню</a><br />
    <a href="<?=my7::baseurl()?>a7-news" target="right">Новости</a><br />
    <a href="<?=my7::baseurl()?>a7-newsto" target="right">Новости для туроператоров</a><br />
    <!--- <a href="<?=my7::baseurl()?>a7-otz" target="right">Отзывы</a><br />-->
    <a href="<?=my7::baseurl()?>a7-left/treedopmenu">Дополнительное меню</a><br />
    <a href="<?=my7::baseurl()?>a7-left/tours">Туры</a><br />
    <a href="<?=my7::baseurl()?>a7-left/qa">Вопросы - ответы</a><br />
    <a href="<?=my7::baseurl()?>tools/helpers/goedittitle">Редактирование заголовков страниц (SEO)</a><br />
    <!--<a href="<?=my7::baseurl()?>a7-left/heditconf">Конфиденциальная инфа для туроператоров</a><br />-->
    <a href="<?=my7::baseurl()?>a7-zayav" target="right">Заявки на доступ туроператоров</a><br />
    <a href="<?=my7::baseurl()?>a7-left/gostcor">Гостиницы Кореи</a><br />
    <a href="<?=my7::baseurl()?>a7-left/touropmenu">Туроператорам</a><br />
    <a href="<?=my7::baseurl()?>a7-settings" target="right">Спецпредложение</a><br />
    <a href="<?=my7::baseurl()?>a7-left/video">Видео о Корее</a><br />
    <a href="<?=my7::baseurl()?>a7-left/logout">Выход из модуля адмиинистратора</a><br />

    <? /*<a href="<?=my7::baseurl()?>a7-article3" target="right">Спецпредложения</a><br />
    <a href="<?=my7::baseurl()?>a7-hedit/index/id/banners" target="right">Баннеры</a><br />
    <a href="<?=my7::baseurl()?>a7-left/treepub">Публикации</a><br />
    <a href="<?=my7::baseurl()?>a7-left/pagesetup">Настройка контактной информации на странице</a><br />
    <br />
    ?><?/*
    <a href="<?=my7::baseurl()?>ta_hedit/index/id/5" target="right">777</a><br />
<a href="<?=$this->baseUrl()?>/a7-news" target="right">Новости</a><br/>
<a href="<?=$this->baseUrl()?>/a7-article2" target="right">Актуальные события</a><br/>
<a href="<?=$this->baseUrl()?>/a7-table1" target="right">План проверок</a><br/>
<a href="<?=$this->baseUrl()?>/a7-table2" target="right">Реестр членов ТМФ</a><br/>
<a href="<?=$this->baseUrl()?>/a7-hedit-files/index/id/1" target="right">Нормативные документы</a><br/>
<a href="<?=$this->baseUrl()?>/a7-hedit-files/index/id/2" target="right">Учредительные документы</a><br/>
<a href="<?=$this->baseUrl()?>/a7-settings" target="right">Настройки сайта</a><br/>
Страницы:<br />
&nbsp;<a href="<?=$this->baseUrl()?>/a7-hedit/index/id/welcome" target="right">Блок "Добро пожаловать"</a><br/>
&nbsp;<a href="<?=$this->baseUrl()?>/a7-hedit/index/id/info" target="right">Информация</a><br/>
&nbsp;<a href="<?=$this->baseUrl()?>/a7-hedit/index/id/contacts" target="right">Контакты</a><br/>
&nbsp;<a href="<?=$this->baseUrl()?>/a7-hedit/index/id/requirements" target="right">Требования к выдаче свидетельства о допуске</a><br/>
&nbsp;<a href="<?=$this->baseUrl()?>/a7-hedit/index/id/learn" target="right">Обучение</a><br/>
&nbsp;<a href="<?=$this->baseUrl()?>/a7-hedit/index/id/togo" target="right">Схема проезда</a><br/>
<br/><br/>
<a href="<?=$this->baseUrl()?>/tools/helpers/goedittitle/">Редактирование заголовков страниц (SEO)</a>
*/    ?>
</nobr>

