<nobr>
    <a href="<?=my7::baseurl()?>a7-left">На главную страницу</a><br/><hr />
    <a href="<?=my7::baseurl()?>a7-hedit/index/id/index" target="right">Главная страница / US Travel</a><br />
    <a href="<?=my7::baseurl()?>a7-hedit/index/id/about" target="right">О нас</a><br />
    <? /*<a href="<?=my7::baseurl()?>a7-hedit/index/id/actions" target="right">Акции и скидки</a><br />
    <a href="<?=my7::baseurl()?>a7-hedit/index/id/useful" target="right">Полезно знать</a><br />*/ ?>
    <a href="<?=my7::baseurl()?>a7-hedit/index/id/contacts" target="right">Контакты</a><br />
    <a href="<?=my7::baseurl()?>a7-hedit/index/id/info" target="right">Полезные ссылки</a><br />
    <a href="<?=my7::baseurl()?>a7-hedit/index/id/conf" target="right">Конф.инфо для туроператоров (не используется)</a><br />
    <br>
    <?/*<a href="<?=my7::baseurl()?>a7-hash" target="right">Отправка писем с адресом личной страницы<br>&nbsp;для замены
        пароля всем пользователям у кого<br>&nbsp; указанный пароль (как у администратора)</a><br />*/?>
</nobr>
<?
//info - полезные ссылки
?>

