<nobr>
    <a href="<?=my7::baseurl()?>a7-left">На главную страницу</a><br/><hr />
    <a href="<?=my7::baseurl()?>a7-hedit/index/id/topright" target="right">Верхняя правая часть</a><br />
    <a href="<?=my7::baseurl()?>a7-hedit/index/id/bottomleft" target="right">Нижняя левая часть</a><br />
    <a href="<?=my7::baseurl()?>a7-hedit/index/id/bottomcenter" target="right">Нижняя часть страницы по центру</a><br />
</nobr>

