<?php
/*
Copyright (C) 2010 Александр Воробьев
 * показывает дерево из pfx_tree с указанным идентификатором
 */
?>
<?
if ($this->updaterightsave) {
?>
<script type="text/javascript">
<?
if ($this->updaterightsave==2) {
?>
var oIframe = top.document.getElementById('right').contentWindow.updateerrupload5();
<?
} else {
?>
var oIframe = top.document.getElementById('right').contentWindow.updatesave5();
<?
}
?>
</script>
<?
};
?>

<nobr>
    <a href="<?=my7::baseurl()?>a7-left/index/updright/1">На главную страницу</a><br/><hr />
    <h4 align="center">Туроператорам</h4>
<?
$tr=new My_itdbtr(my7::getdbprefix().'tree');
$tr->idtree=12;
$tr->show('ta_heditourop',my7::curaction(), false);
?>
</nobr>
