<script language="JavaScript">
function delr(id) {
if (confirm('Вы уверены, что хотите удалить этот элемент?')) {
 window.location.href='<?=my3::baseurl()?>a7-news/rdel/id/'+id;
 };
};
function izm(id) {
window.location.href='<?=my3::baseurl()?>a7-news/edit/id/'+id;
};
</script>
<div align="center">
<h1 align="center">Новости</h1>
<a href="<?=my3::baseurl()?>a7-news/edit/id/0">Добавить новость</a><br>
<br>
<table border="1" cellpadding="3" cellspacing="0">
<tr valign="top">
<th>Дата</th><th>Название новости</th><th>Действия</th>
</tr>
<?
for ($i=0;$i<count($this->arr);$i++) {
 $row=$this->arr[$i];
 $uid2=$row->uid;
 echo '<tr align="left"><td valign=top>'.$row->df;
 echo '</td>';
 echo '<td valign=top>'.nl2br($this->escape($row->naim));
 echo '</td><td valign=top><input type="button" onclick="javascript:izm('.$uid2.');" value="Изменить"><input type="button" onclick="javascript:delr('.$uid2.');" value="Удалить">';
 echo '</td></tr>';
}
?>
</table>
</div>
<? my3::printpages($this->lend); ?>