<?
//$o4=new My_PageEffects();
//echo $o4->hidingmessage('gfdhdg');
?>
<?
my3::inithtmleditor();

//echo $this->row->html;
	echo '<form action="'.$this->baseUrl().'/'.my3::nctrl().'/save/id/'.$this->sid.'" method="post" style="margin:0;padding:0;">';
	//echo '<input type="hidden" name="rsid" value="'.$sid2.'">';
	echo '<h2 align=center>'.$this->escape($this->row->naim).'</h2>';
/*include("../spaw2/spaw.inc.php");
$spaw = new SpawEditor("html", $row->html);
$spaw->show();*/
?>
		<div id="accordion">
			<div>
				<h3><a href="#">Страница</a></h3>
                                <div style="height:370px">
<?
        my3::editorfield('html',$this->row->html,'','300'); 
?>
                                </div>
			</div>
			<div>
				<h3><a href="#">Title,Description,Keywords</a></h3>
				<div>
                                    Title: <input type="text" name="title" size="80" style="width:100%"
                                                  value="<?=my3::nbsh($this->kw->data->title)?>"><br />
                                    Description: <br />
                                    <textarea name="description" cols="60" rows="4" style="width:100%"><?=my3::nbsh($this->kw->data->description)?></textarea>
                                    <br />
                                    Keywords (через запятую): <input type="text" name="keywords" size="80" style="width:100%"
                                                  value="<?=my3::nbsh($this->kw->data->keywords)?>"><br />
                                    * примечание: если не заполнять эти поля, то на сайте будут подставлены значения по умолчанию
                                </div>
			</div>
		</div>
<script type="text/javascript">
$(function(){

        // Accordion
        $("#accordion").accordion({ header: "h3",fillSpace:true });

});
</script>
<?
        /*if ($sid2=='contact') {
	 $row9=qobj("select html from av_html where sid='contact2'");
     echo '<br>
<br>
Код карты:<br>
<textarea name="kodd" cols="60" rows="7">'.htmlspecialchars($row9->html).'</textarea><br>';
	 };*/
	echo '<br /><div class="savediv"><input type="submit" value="Сохранить"></div></form>';
?>