<?php 
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle(isset($this->title) ? $this->escape($this->title) : 'Администраторский модуль');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/admin.css'); ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/ui-lightness/jquery-ui-1.8.18.custom.css'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-1.7.1.min.js'); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui-1.8.18.custom.min.js'); ?>
    </head>
    <body<?=isset($this->bodyclass) ? ' class="'.$this->bodyclass.'"' : ''?>>
        <?/*<h1><?php echo $this->escape($this->title); ?></h1>*/?>
        <?
        /*// отображаем форму работы с деревом, если нужно
        $id=$this->getParam('id',0);
        $this->action('getforminfo',
                'treeform',$id);*/
        ?>
        <?php echo $this->layout()->content; ?>
    </body>
</html>
