<?
if (!$this->id && !$this->idtree) {
    echo str_repeat('<br />',10).
            '<p align="center">Эта запись удалена</p>';
    exit;
}
my3::inithtmleditor();
?>


<?
//echo $this->row->html;
$s4=$this->baseUrl();
echo '<form enctype="multipart/form-data" target="lfr" action="'.$this->baseUrl().'/'.strtolower(my3::nctrl()).'/save/id/'.$this->id.
        ($this->leftview ? '/leftview/'.my3::nbsh($this->leftview) : '').'" method="post">';
//echo '<input type="hidden" name="rsid" value="'.$sid2.'">';
//echo $this->id;
echo '<h2 align=center>'.($this->id ? '' : 'Добавление новой записи').'
    </h2>';
if (!$this->id) echo '<input type="hidden" name="idtree" value="'.$this->idtree.'" />';
/*include("../spaw2/spaw.inc.php");
$spaw = new SpawEditor("html", $row->html);
$spaw->show();*/
//var_dump($this->view,$this->id);
/*if ($this->row->idtree==2 && $this->id)
        echo '<p align="center">Адрес страницы на сайте:
            <a href="http://'.$_SERVER['SERVER_NAME'].my3::baseurl().'cat/'.$this->id.'" target="_blank">http://'.
            $_SERVER['SERVER_NAME'].
            my3::baseurl().'cat/'.$this->id.'</a></p>';*/
echo 'Название: <input type="text" size="50" name="naim" value="'.my3::nbsh($this->row->naim).'" />';

?>
		<div id="accordion">
			<div>
				<h3><a href="#">Страница</a></h3>
                                <div style="height:520px">
<?
//echo '<br /><div class="savediv" style="text-align:right"><input type="submit" value="Сохранить"></div>';

echo 'Изображение:<br>';
$img_dir=my3::basepath().'img2/';
$img_http=my3::baseurl().'img2/';
$noimg=($this->row->pict=='' || ($szs=@getimagesize($img_dir.$this->row->pict))===false || $szs[0]==0);
if (!$this->id || $noimg) {
    echo '<font color=green>Нет изображения</font>';
} else {
    echo '<img src="'.$img_http.$this->row->pict.'" '.$szs[3].'>';
}
echo '<br />';
echo 'Добавить/заменить изображение: <input name="userfile[]" type="file"><br>';
echo 'Максимальный размер изображения: '.ini_get('upload_max_filesize').'б';
if ($this->id) {
    echo '<br><input name="img_del1" type="checkbox" id=dd1><label for=dd1>Удаление изображения</label>';
};
echo '<br /><br />';
if (true) { // $this->row->topid==299
    // подраздел "цены и туры"
    echo '<input name="prost1" type="checkbox" id=dd18><label for=dd18>Сделать этот тур доступным всем туроператорам</label><br><br />';
    
}
?>
                                <input type="checkbox" id="newtour" name="newtour" <?=($this->row->newtour ? 
        'checked="checked"' : '')?> /> <label for="newtour">Признак нового тура</label><br /><br />
<?
my3::editorfield('html',$this->row->html,'','290');
?>
                                </div>
			</div>
			<div>
				<h3><a href="#">Title,Description,Keywords</a></h3>
				<div>
                                    Title: <input type="text" name="title" size="80" style="width:100%"
                                                  value="<?=my3::nbsh($this->kw->data->title)?>"><br />
                                    Description: <br />
                                    <textarea name="description" cols="60" rows="4" style="width:100%"><?=my3::nbsh($this->kw->data->description)?></textarea>
                                    <br />
                                    Keywords (через запятую): <input type="text" name="keywords" size="80" style="width:100%"
                                                  value="<?=my3::nbsh($this->kw->data->keywords)?>"><br />
                                    * примечание: если не заполнять эти поля, то на сайте будут подставлены значения по умолчанию
                                </div>
			</div>
		</div>
<script type="text/javascript">
$(function(){

        // Accordion
        $("#accordion").accordion({ header: "h3",fillSpace:true });

});
</script>

<?


/*if ($sid2=='contact') {
	 $row9=qobj("select html from av_html where sid='contact2'");
     echo '<br>
<br>
Код карты:<br>
<textarea name="kodd" cols="60" rows="7">'.htmlspecialchars($row9->html).'</textarea><br>';
	 };*/

$o4=new My_PageEffects();
echo $o4->uploaderrormessage('Ошибка загрузки файла');

echo '<br /><div class="savediv"><input type="submit" value="Сохранить"></div></form>';
?>