<br />
<br />
<br />
<br />
<br />
<br />
<form action="a7/login" method="post" name="fm1">
<p align="center">
<b>Введите пароль администратора:</b><br><br>
<input name="pwd" type="password" size="20" maxlength="20"><br>
<?php
//echo '<img src="tools/graphics.php?r='.rand(1,1000000).'">';
?>
<br><b>Введите число указанное на рисунке</b><br><br>
<img src="<?=my3::baseUrl()?>kcaptcha/index.php?<?php echo session_name()?>=<?php echo session_id()?>" border="0" width="120" height="60" /><br />
<br />
<input type="text" name="keystring" size="6" />
<br><br>
<?php
if (isset($_GET['t']))
	{
	echo '<input type="hidden" name="ttt" value="1">';
	};
?>
<input name="sb" type="submit" value="Ввод">
</p>
