<?
my3::inithtmleditor();

//echo $this->row->html;
echo '<form action="'.$this->baseUrl().'/'.my3::nctrl().'/save/id/'.$this->id.'" method="post" enctype="multipart/form-data">';
//echo '<input type="hidden" name="rsid" value="'.$sid2.'">';
echo '<h2 align=center>'.my3::nbsh($this->row->naim).'</h2>';
my3::showerror();

/*include("../spaw2/spaw.inc.php");
$spaw = new SpawEditor("html", $row->html);
$spaw->show();*/
my3::editorfield('html',$this->row->html,'','400');
/*if ($sid2=='contact') {
	 $row9=qobj("select html from av_html where sid='contact2'");
     echo '<br>
<br>
Код карты:<br>
<textarea name="kodd" cols="60" rows="7">'.htmlspecialchars($row9->html).'</textarea><br>';
	 };*/
echo '<br /><h4 align="center">Документы</h4>';
$o2=new My_plusminusstruct();
$arr=explode(';',$this->row->files);
echo $o2->gethtml($arr);
echo '<br /><div class="savediv"><input type="submit" value="Сохранить"></div></form>';
?>