<?
$b2=($this->flt596=='');
?>
<script language="JavaScript">
function delr(id) {
if (confirm('Вы уверены, что хотите удалить этот элемент?')) {
 window.location.href='<?=my3::baseurl()?>a7-zayav/rdel/id/'+id;
 };
};
function izm(id) {
window.location.href='<?=my3::baseurl()?>a7-zayav/edit/id/'+id;
};
</script>
<div align="center">
    <a href="<?=my3::baseurl()?>a7-zayav/xls">Заявки ТО в виде Excel файла</a><br />
<h1 align="center">Заявки туроператоров на доступ к конфиденциальной информации</h1>
<p align="center">(серым цветом выделены не одобренные (пока?) заявки)</p>
<p align="center"><form method="post" action="<?=my3::baseurl()?>a7-zayav/filter">Фильтр
    по названию фирмы и E-mail: <input type="text" name="filter"
   value="<?=my3::nbsh($this->flt596)?>" /> 
    <input type="submit" value="Применить" />
</form>
</p>
<!--<a href="<?=my3::baseurl()?>a7-news/edit/id/0">Добавить новость</a><br>-->
<br>
<table border="1" cellpadding="3" cellspacing="0">
<tr valign="top">
<?=($b2 ? '<th>Порядк. номер</th>' : '')?><th>Дата отправки заявки</th><th>Фирма</th><th>E-mail</th><th>Действия</th>
</tr>
<?
$psort = $this->psort;
for ($i=0;$i<count($this->arr);$i++) {
 $row=$this->arr[$i];
 $uid2=$row->uid;
 echo '<tr align="left" '.($row->ismoderated ? '' : 'style="background-color:grey"').'>'.
     ($b2 ? '<td style="padding-left:40px">'.$psort.'</td>' : '').
     '<td valign=top>'.$row->df;
 echo '</td>';
 echo '<td valign=top>'.nl2br($this->escape($row->naimfirm));
 echo '</td>';
 echo '<td valign=top>'.nl2br($this->escape($row->email));
 echo '</td><td valign=top><nobr><input type="button" onclick="javascript:izm('.$uid2.');" value="Изменить"><input type="button" onclick="javascript:delr('.$uid2.');" value="Удалить"></nobr>';
 echo '</td></tr>';
 $psort--;
}
?>
</table>
</div>
<? my3::printpages($this->lend); ?>