<?
echo '<form action="'.$this->baseUrl().'/a7-settings/save" method="post" style="margin:0;padding:0;">';
?>
<h2 align="center">Редактирование настроек сайта</h2>
<?
my7::showerror();
/*
Количество новостей на главной странице: <input type="text" name="numnews" size="5" maxlength="200" value="<?=htmlspecialchars($this->row->numnews)?>" /><br>
Количество событий выводимых на главной странице: <input type="text" name="numarticles" size="5" maxlength="200" value="<?=htmlspecialchars($this->row->numarticles)?>" /><br>
*/
?>
Текст спецпредложения:<br>
<textarea name="spec" cols="60" rows="5"><?=htmlspecialchars($this->row->spec)?></textarea>
<br><br>
Адрес ссылки для спецпредложения: <input type="text" name="hrefspec" size="70" maxlength="200" value="<?=htmlspecialchars($this->row->hrefspec)?>" /><br>
<br>
Основной E-mail администратора сайта: <input type="text" name="siteemail" size="70" maxlength="200" value="<?=htmlspecialchars($this->row->siteemail)?>" /><br>
<br>
Количество отправляемых почтовых сообщений раз в 10 минут в списках рассылки: <input type="text" size="5" name="every10minutesnummails" maxlength="200" value="<?=htmlspecialchars($this->row->every10minutesnummails)?>" /><br>
(рекомендуемое значение 15, хотя может отправить и 120 сообщений за раз, но не гарантировано что они все правильно
отправятся, при этом сообщений об ошибке может и не быть)
<br>
<hr>
<span style="color:red">Системные переменные, не менять!</span><br><br>
Количество почты отправленной с сайта помимо списков рассылки в последние 10 минут (moremailsent): <input type="text" size="5" name="moremailsent"maxlength="200" value="<?=htmlspecialchars($this->row->moremailsent)?>" /><br>
<br>
<a href="<?=my7::baseurl()?>a7-tracemail">Отслеживание работы почтовых рассылок</a>
<?
	echo '<br /><div class="savediv"><input type="submit" value="Сохранить"></div></form>';
?>