<?
my3::inithtmleditor();
//echo $this->row->html;
	echo '<form action="'.my3::baseurl().my3::nctrl().'/save/id/'.$this->id.'" method="post" style="margin:0;padding:0;"  enctype="multipart/form-data">';

?>
<h2 align="center">Редактирование актуального события</h2>
<?
my3::showerror();
?>
Наименование: <input type="text" name="naim" size="50" maxlength="200" value="<?=htmlspecialchars($this->row->naim)?>" /><br>
<br>Краткое описание:<br>
<textarea name="anons" cols="60" rows="5" style="width:100%"><?php echo htmlspecialchars($this->row->anons); ?></textarea><br>
<br>Подробное описание:<br>
<?
        my3::editorfield('html',$this->row->html,'','400');

echo '<br>Изображение:<br>';
$img_dir=my3::basepath().'img2/';
$img_http=my3::baseurl().'img2/';
$noimg=($this->row->pict=='' || ($szs=@getimagesize($img_dir.$this->row->pict))===false || $szs[0]==0);
if (!$this->id || $noimg) {
    echo '<font color=green>Нет изображения</font>';
} else {
    echo '<img src="'.$img_http.$this->row->pict.'" '.$szs[3].'>';
}
echo '<br />';
echo 'Добавить/заменить изображение: <input name="userfile[]" type="file"><br>';
echo 'Максимальный размер изображения: '.ini_get('upload_max_filesize').'б';
if ($this->id) {
    echo '<br><input name="img_del1" type="checkbox" id=dd1><label for=dd1>Удаление</label><br>';
};

echo '<br /><div class="savediv"><input type="submit" value="Сохранить"></div></form>';
?>