<?
//my7::inithtmleditor();
$items=$this->items;
?>
<form action="<?=my7::baseurl().my7::nctrl().'/save/id/'.$this->id?>" method="post" style="margin:0;padding:0;"  enctype="multipart/form-data">
    <h2 align="center">Редактирование реестра членов ТМФ </h2>
    <?
    my7::showerror();
    ?>
    <table class="edittable" border="1" cellpadding="3" cellspacing="0">
        <tr>
            <td>ИНН</td>
            <td><input type="text" name="s1" size="50" maxlength="200"
                       value="<?=my7::nbsh($items->s1)?>" />
            </td>
        </tr>
        <tr>
            <td>
Полное наименование юридического лица, его адрес (место нахождения), фамилия, имя и отчество индивидуального предпринимателя, дата его рождения, место жительства             </td>
            <td><textarea name="s2" style="width:100%" rows="4"><?=my7::nbsh($items->s2)?></textarea>
            </td>
        </tr>
        <tr>
            <td>
Номер и дата выдачи Свидетельства о допуске к видам работ, которые оказывают влияние на безопасность объектов капитального строительства             </td>
            <td><textarea name="s3" style="width:100%" rows="4"><?=my7::nbsh($items->s3)?></textarea>
            </td>
        <tr>
            <td>
Перечень видов работ, которые оказывают влияние на безопасность объектов капитального строительства и к которым член СРО имеет Свидетельство о допуске             </td>
            <td><textarea name="s4" style="width:100%" rows="4"><?=my7::nbsh($items->s4)?></textarea>
            </td>
        </tr>
        <tr>
            <td>
Сведения о приостановке действия Свидетельства о допуске члена СРО
            </td>
            <td><textarea name="s5" style="width:100%" rows="4"><?=my7::nbsh($items->s5)?></textarea>
            </td>
        </tr>
        <tr>
            <td>
Сведения о возобновлении действия Свидетельства о допуске члена СРО
            </td>
            <td><textarea name="s6" style="width:100%" rows="4"><?=my7::nbsh($items->s6)?></textarea>
            </td>
        </tr>
        <tr>
            <td>
Сведения об отказе в возобновлении действия Свидетельства о допуске члена СРО
            </td>
            <td><textarea name="s7" style="width:100%" rows="4"><?=my7::nbsh($items->s7)?></textarea>
            </td>
        </tr>
        <tr>
            <td>
Сведения о прекращении действия Свидетельства о допуске члена СРО к определенному виду или видам работ, которые оказывают влияние на безопасность объектов капитального строительства             </td>
            <td><textarea name="s8" style="width:100%" rows="4"><?=my7::nbsh($items->s8)?></textarea>
            </td>
        </tr>
        <tr>
            <td>
Сведения о внесении изменений в Свидетельство о допуске к виду или видам работ, которые оказывают влияние на безопасность объектов капитального строительства             </td>
            <td><textarea name="s9" style="width:100%" rows="4"><?=my7::nbsh($items->s9)?></textarea>
            </td>
        </tr>
        <tr>
            <td>
Телефон, адрес электронной почты, адрес сайта в сети «Интернет»
            </td>
            <td><textarea name="s10" style="width:100%" rows="4"><?=my7::nbsh($items->s10)?></textarea>
            </td>
        </tr>
        <tr>
            <td>
Примечание
            </td>
            <td><textarea name="s11" style="width:100%" rows="4"><?=my7::nbsh($items->s11)?></textarea>
            </td>
        </tr>
    </table>
    <br /><div class="savediv"><input type="submit" value="Сохранить"></div></form>